extends:
  - eslint:recommended
  - plugin:prettier/recommended
env:
  browser: true
  es2020: true
  node: true
plugins:
  - prettier
rules:
  prettier/prettier: error
parserOptions:
  ecmaVersion: 11
  sourceType: module
