extends:
  - eslint:recommended
env:
  browser: true
  es2020: true
  node: true
  jest: true
plugins:
  - svelte3
overrides:
  - files: ['*.svelte']
    processor: svelte3/svelte3
parserOptions:
  sourceType: module
