// we use constants instead of static class fields to break cyclic dependencies which Jest struggles with.
export const AnchorBehaviorName = 'anchorable'
export const AnimateBehaviorName = 'animatable'
export const DetailBehaviorName = 'detailable'
export const DrawBehaviorName = 'drawable'
export const FlipBehaviorName = 'flippable'
export const LockBehaviorName = 'lockable'
export const MoveBehaviorName = 'movable'
export const RotateBehaviorName = 'rotable'
export const StackBehaviorName = 'stackable'
export const TargetBehaviorName = 'targetable'
