name: CD

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  buildAndDeploy:
    name: Build and deploy

    # either triggered manually, or when CI completed on main branch
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    runs-on: ubuntu-latest

    steps:
      - name: Check code out
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Intall Pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Set Node.js up
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Build artifacts
        run: ./hosting/build.sh

      - name: Upload to VPS and trigger deployment
        run: ./hosting/upload.sh
        env:
          USER: ${{ secrets.DEPLOY_USERNAME }}
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          HOST: ${{ secrets.DEPLOY_HOST }}
          PORT: ${{ secrets.DEPLOY_PORT }}
