name: CD

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  buildAndDeploy:
    name: Build and deploy

    # either triggered manually, or when CI completed, and it was not on a PR
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && !github.event.workflow_run.head_branch) }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Check code out
        uses: actions/checkout@v2

      - name: Set Node.js ${{ matrix.node-version }} up
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build artifacts
        run: ./hosting/build.sh

      - name: Upload to VPS and trigger deployment
        run: ./hosting/upload.sh
        env:
          USER: ${{ secrets.DEPLOY_USERNAME }}
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          HOST: ${{ secrets.DEPLOY_HOST }}
          PORT: ${{ secrets.DEPLOY_PORT }}
