name: CD

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  buildAndDeploy:
    name: Build and deploy

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Check code out
        uses: actions/checkout@v2

      - name: Set Node.js ${{ matrix.node-version }} up
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build artifacts
        run: npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$KEY" > ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host vps
              HostName $HOST
              Port $PORT
              User $USER
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no
          END
        env:
          USER: ${{ secrets.DEPLOY_USERNAME }}
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          HOST: ${{ secrets.DEPLOY_HOST }}
          PORT: ${{ secrets.DEPLOY_PORT }}

      - name: Upload UI files to VPS
        run: scp -r apps/web/dist vps:~/web/dist

      - name: Upload server files to VPS
        run: scp -r apps/server/dist vps:~/server/dist

      - name: Trigger deployment
        run: ssh vps '~/server/deploy.sh'
