name: CD

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  buildAndDeploy:
    name: Build and deploy

    # either triggered manually, or when CI completed on main branch
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Check code out
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set Node.js ${{ matrix.node-version }} up
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --omit=dev --ignore-scripts

      - name: Build artifacts
        run: ./hosting/build.sh
        env:
          WEB_GAME_ASSETS_URL: https://tabulous.fr/games
          WEB_GRAPHQL_URL: https://tabulous.fr/graphql

      - name: Upload to VPS and trigger deployment
        run: ./hosting/upload.sh
        env:
          USER: ${{ secrets.DEPLOY_USERNAME }}
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          HOST: ${{ secrets.DEPLOY_HOST }}
          PORT: ${{ secrets.DEPLOY_PORT }}
