name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    name: Lint and format code

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check code out
        uses: actions/checkout@v3

      - name: Set Node.js ${{ matrix.node-version }} up
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Check linter violations
        run: npm run lint

      - name: Check code format
        run: npm run format -- --check

  test:
    name: Run tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check code out
        uses: actions/checkout@v2

      - name: Set Node.js ${{ matrix.node-version }} up
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run CLI test
        run: npm run test:cli

      - name: Run server test
        run: npm run test:server

      - name: Run UI unit tests
        run: |
          mkdir -p apps/web/.svelte-kit/runtime
          cp -r node_modules/@sveltejs/kit/assets/* apps/web/.svelte-kit/runtime
          npm run test:web
        env:
          WEB_GAME_ASSETS_URL: https://localhost:3000/games
          WEB_GRAPHQL_URL: https://localhost:3000/graphql

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run UI integration tests
        run: npm run test:integration
        env:
          WEB_GAME_ASSETS_URL: http://localhost:3001/games
          WEB_GRAPHQL_URL: http://localhost:3001/graphql
          WEB_AUTH_URL: http://localhost:3001/auth
          WEB_USE_GITHUB_PROVIDER: true
          WEB_USE_GOOGLE_PROVIDER: true

      - name: Send coverage to Codacy
        if: always()
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: apps/cli/coverage/clover.xml,apps/server/coverage/clover.xml,apps/web/coverage/clover.xml,apps/web/coverage/clover-integration.xml
