name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    name: Lint and format code

    runs-on: ubuntu-latest

    steps:
      - name: Check code out
        uses: actions/checkout@v3

      - name: Set Node.js up
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  cli_tests:
    name: CLI tests

    runs-on: ubuntu-latest
    needs: [lint-and-format]

    steps:
      - name: Check code out
        uses: actions/checkout@v2

      - name: Set Node.js up
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run CLI test
        run: npm run test:cli

      - name: Send coverage to Codacy
        if: always()
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: apps/cli/coverage/clover.xml

  server_tests:
    name: Server tests

    runs-on: ubuntu-latest
    needs: [lint-and-format]

    steps:
      - name: Check code out
        uses: actions/checkout@v2

      - name: Set Node.js up
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run server test
        run: npm run test:server

      - name: Send coverage to Codacy
        if: always()
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: apps/server/coverage/clover.xml

  web_tests:
    name: Web unit tests

    runs-on: ubuntu-latest
    needs: [lint-and-format]

    steps:
      - name: Check code out
        uses: actions/checkout@v2

      - name: Set Node.js up
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run UI unit tests
        run: npm run test:web
        env:
          WEB_GAME_ASSETS_URL: https://localhost:3000/games
          WEB_GRAPHQL_URL: https://localhost:3000/graphql

      - name: Send coverage to Codacy
        if: always()
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: apps/web/coverage/clover.xml

  integration_tests:
    name: Web integration tests

    runs-on: ubuntu-latest
    needs: [lint-and-format]

    steps:
      - name: Check code out
        uses: actions/checkout@v2

      - name: Set Node.js up
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run UI integration tests
        run: npm run test:integration
        env:
          WEB_GAME_ASSETS_URL: http://localhost:3001/games
          WEB_GRAPHQL_URL: http://localhost:3001/graphql
          WEB_AUTH_URL: http://localhost:3001/auth
          WEB_USE_GITHUB_PROVIDER: true
          WEB_USE_GOOGLE_PROVIDER: true

      - name: Send coverage to Codacy
        if: always()
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: apps/web/coverage/clover-integration.xml
